WIP

diff --git a/.travis.yml b/.travis.yml
--- a/.travis.yml
+++ b/.travis.yml
@@ -23,13 +23,13 @@ env:
     - LIBJEMALLOC_DEB="libjemalloc1_3.5.1-2_amd64.deb"
     - LIBPCRE_DEB="libpcre3_8.31-2ubuntu2.3_amd64.deb"
     - VARNISH_DEB="varnish_4.1.0-1~trusty_amd64.deb"
-    - OSF_DB_PORT="54321"
+    - OSF_DB_PORT="5432"
   matrix:
     - TEST_BUILD="osf"
-    - TEST_BUILD="else"
-    - TEST_BUILD="api1"
-    - TEST_BUILD="api2"
-    - TEST_BUILD="api3"
+    # - TEST_BUILD="else"
+    # - TEST_BUILD="api1"
+    # - TEST_BUILD="api2"
+    # - TEST_BUILD="api3"
     # - TEST_BUILD="varnish"
 
 before_install:
@@ -58,7 +58,7 @@ before_install:
       sed -i -e 's/#fsync.*/fsync = off/' /tmp/postgres/data/postgresql.conf
       sed -i -e 's/#synchronous_commit.*/synchronous_commit = off/' /tmp/postgres/data/postgresql.conf
       sed -i -e 's/#full_page_writes.*/full_page_writes = off/' /tmp/postgres/data/postgresql.conf
-      /tmp/postgres/usr/lib/postgresql/9.6/bin/postgres -k /tmp -D /tmp/postgres/data -p 54321 > /dev/null & export POSTGRES_PID=$!
+      /tmp/postgres/usr/lib/postgresql/9.6/bin/postgres -k /tmp -D /tmp/postgres/data -p 5432 > /dev/null & export POSTGRES_PID=$!
     # elasticsearch
     - |
       cd $HOME/.cache/downloads
@@ -121,6 +121,14 @@ install:
     - pip uninstall uritemplate.py --yes
     - pip install uritemplate.py==0.3.0
     - travis_retry invoke assets --dev
+
+before_script:
+    - psql -c 'create database osf;' -U postgres
+    - |
+      if ! invoke make_migrations | grep -q "No changes detected"; then
+        echo "Build failed on makemigrations"
+        exit 1
+      fi
 
 # Run Python tests (core and addon) and JS tests
 script:
